license="CC0-1.0"


[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
description='''${description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_loader_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"


[[dependencies.${mod_id}]]
    modId="codxlib"
    type="required"
    versionRange="[0.1.0,)"
    ordering="AFTER"
    side="BOTH"
