plugins {
    // see https://fabricmc.net/develop/ for new versions
    id 'net.fabricmc.fabric-loom' version '1.15.5' apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '2.0.141' apply false
    // see https://maven.minecraftforge.net/net/minecraftforge/gradle/ForgeGradle/
    id 'net.minecraftforge.gradle' version '[7.0.17,8)' apply false
}

subprojects {
    version = rootProject.mod_version
    group = rootProject.mod_group
    description = rootProject.mod_description
}
